[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/guvendemirel/QMULSBM_PhDWorkshop/blob/master/SBM_PhD_python_ws_part1and2.ipynb)

# SBM PhD workshop Part 2

## Data Extraction, Cleaning, and Exploration with Python Part 2

This is the [Python](https://www.python.org/) programming tutorial part 3. In this session, we will continue our introduction to programming with Python. We will learn about control flow with conditional statements and `for` loops. We will then introduce functions in Python.

## Control Flow

Control flow refers to the specification of the order of execution of different blocks of code using mainly conditional statements and loops. Boolean data type and operations are critical for control flows.

The scalar Boolean data type in Python is `bool`, which has two instances `True` and `False`. 

In [1]:
type(True)

bool

### Boolean Operations
- `a & b`: AND - True if both a and b are True
- `a | b`: OR - True if either a and/or b is True
- `a ^ b`: XOR - True if any one of a or b is True, but not both
- `a == b` True if a equals b
- `a != b` True if a is not equal to b
- `a <= b, a < b`	True if a is less than or equal to (less than) b
- `a > b, a >= b`	True if a is greater than or equal to (greater than) b
- `a is b`	True if a and b reference the same Python object
- `a is not b`	True if a and b reference different Python objects

In [2]:
# What outputs do you expect?
print(True & False)
print(True ^ True)

False
False


In [3]:
list1 = [1, 2, 0]
list2 = [1, 2, 0]
# What output do you expect?
print(list1 == list2, list1 is list2)

True False


In [4]:
list3 = list1
# What output do you expect?
print(list2 == list3, list1 is list3, list2 is list3)

True True False


## Choice Statements:
Choice statements control the flow in the program depending on which condition is met.
```pyton
if condition1:
    statement1
elif condition2:
    statement2
elif condition3:
    statement3
else:
    statement4
```

As an example, we will generate two standard normal variables and choose the greater value. 

In [5]:
import numpy as np

np.random.seed(42) #set the seed for pseudo-random numbers 

# a standard normal random number 
x = np.random.standard_normal() 

# generate another standard normal random number
y = np.random.standard_normal() 

# format replaces the {} in the string with the corresponding argument
print("x={0:.2f} and y={1:.2f}".format(x, y)) 

x=0.50 and y=-0.14


In [6]:
# Print the maximum of x and y
if x>=y: 
    print("Maximum is x={0:.2f}".format(x))
else:
    print("Maximum is y= {0:.2f}".format(y))

Maximum is x=0.50


In [7]:
import numpy as np

## Loops 

`for` loops are used for iterating over collections, such as lists, tuples, and any iterators. 

`range` function is used to create iterators. It is called by `range(1,5)`, which iterates as 1, 2, 3, and 4. The advantage of iterators as opposed to lists or tuples is that you do not keep the full list. We need only the value in a specific iteration, which saves a lot of memory if looping over a large range.

In Python, `for` loops should only be used in complex situations because they are slower than list comprehensions and Numpy array methods (both to follow). 

If you want to check time performance of an operation you can use the `%%time` and `%%timeit` magics.  

Example: create a loop that calculates the square of one million randomly generated standard normal variables.

In [8]:
# Genereate 1000000 standard normal variables
vals = np.random.standard_normal(1000000)

# Check the type
type(vals)

numpy.ndarray

First, we shall try creating an empty list and the populating it as we loop over the array vals.

In [9]:
%%timeit
# Create an empty list
vals_squared = []
# Loop over the vals array and append to the list the square of the current element
for val in vals: 
    vals_squared.append(val**2)

84.4 ms ± 181 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


We can do the same by first creating a dummy list of the same length as the array, instead of appending an empty list at each iteration. For this, we can use the `enumerate()` function that adds a counter.

In [10]:
%%timeit
# Create a list of None values
vals_squared = 1000000 * [None]
# Loop over the vals array and append to the list the square of the current element
for ind, val in enumerate(vals): 
    vals_squared[ind] = val ** 2

90.6 ms ± 296 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


You can do the same with **list comprehension** in shorter time, which is the Pythonistic way of writing loops by default.

In [11]:
%%timeit
vals_squared = [val ** 2 for val in vals]

80.9 ms ± 194 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


It is even faster to use Numpy methods and operations, which are directly implemented in C.

In [12]:
%%timeit
vals_squared = vals ** 2 # note that this works with Numpy arrays, not lists

613 μs ± 10.9 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In most cases, we need to combine `for` loops with `if else` statements. You can also do this in list comprehensions:

In [13]:
# For the list below
my_list = [1, 10, 'analytics', 'business analytics', 'data', 'machine learning', 'statistics', 'python']

# We want to convert all strings to lowercase (common task in data cleaning) 
# and skip other types 
# Hint: isintance(x,type) checks if x is an instance of class type 
my_cleaned_list = [entry.lower() for entry in my_list if isinstance(entry, str)]

# Print new list
my_cleaned_list

['analytics',
 'business analytics',
 'data',
 'machine learning',
 'statistics',
 'python']

## Functions
Functions are crucial building blocks of programming, which eliminate redundancy and provide abstraction. If you repeat a certain code that solves a non-trivial task in different parts of your code, it is a good indication that you should introduce a function. Organizing your blocks of code into functions provides an abstraction, which makes it easier to understand your code. Furthermore, the maintenance of code is easier with functions. We have so far used several built-in functions, e.g. `print` function, or functions from other packages such as Numpy, e.g. `np.sqrt()`. The functions are called by providing their arguments, lists of which can be checked from the help.

We can also define our own functions. Let's now define a simple function. **Positional arguments** must always be provided inputs. Default values are used for **keyword arguments** if no value is provided. The function definition syntax is as follows:

```python
def function_name(arg1, arg2 = val2):
    code
    return value
```

### Namespaces
The local namespace (variable scope) is created when the function is called and the arguments are automatically loaded. You can also use variables from the global namespace in the local namespace. However, you cannot change their values. If you try, a new variable is created. You must use the `global` keyword if you want to update its value.

As an example, let's write a function that cleans the names of subject areas.

In [18]:
import re #regular expressions library for handling text

courses = [' accounting ', 'finance ', 'Marketing ', 'supply chain management#', '?interna92tional BuSiness1\n']

# Create a list of characters to remove
remove_chars = '[_!#?*0-9]'

def clean_name(name):
    cl_name = name.strip() #remove the beginning and ending white spaces and new lines
    cl_name = re.sub(remove_chars, '', cl_name) #remove unwanted characters
    cl_name = cl_name.title() #first letter capital 
    return cl_name

# Write a list comprehension that applies clean_name to each name in the courses list
cleaned_courses = [clean_name(course) for course in courses]
cleaned_courses

['Accounting',
 'Finance',
 'Marketing',
 'Supply Chain Management',
 'International Business']

Final check about variable scope:

In [15]:
# What happens if you try accessing cl_name outside the function (global scope), where it is not in the namespace?
cl_name

NameError: name 'cl_name' is not defined

In [19]:
# Try the following code - Version 1

def clean_name(name):
    name = name.strip() 
    name = re.sub(remove_chars, '', name) 
    name = name.title()
    return name

name1 = "?businesS analytics#"
name2 = clean_name(name1)

# What output do you expect and why?
print(name1, name2)

?businesS analytics# Business Analytics


In [20]:
# Try the following code - Version 2
def clean_name_alt(name):
    name1 = name.strip() 
    name1 = re.sub(remove_chars, '', name1) 
    name1 = name1.title() #first letter capital 
    return name1

name1 = "something else"
name2 = "?businesS analytics#"
name3 = clean_name_alt(name2)

# What output do you expect and why?
print(name1, name2, name3)

something else ?businesS analytics# Business Analytics


In [21]:
# Try the following code - Version 3
def clean_name_alt(name):
    # Declare the variable as global
    global name1
    name1 = name.strip() 
    name1 = re.sub(remove_chars, '', name1) 
    name1 = name1.title() #first letter capital 
    return name1

name1 = "something else"
name2 = "?businesS analytics#"
name3 = clean_name_alt(name2)

# What output do you expect and why?
print(name1, name2, name3)

Business Analytics ?businesS analytics# Business Analytics


In [22]:
# Check whether name1 and name3 are the same object
name1 is name3

True

In [23]:
# Working with list arguments

# Global scope:
courses = [' accounting ', 'finance ', 'Marketing ', 'supply chain management#', '?interna92tional BuSiness1\n']
no_courses = 0

def clean_names(name_list):
    # set the scope to global
    global no_courses
    # loop over the list by both index and value
    for i, name in enumerate(name_list):
        # increment no_courses
        no_courses += 1
        # call clean_name function and update the list
        name_list[i] = clean_name(name)        

# clean the courses list
clean_names(courses)

# What output do you expect and why?
print(courses, no_courses)

['Accounting', 'Finance', 'Marketing', 'Supply Chain Management', 'International Business'] 5


# Exercise

In [24]:
# Part 1
# import package for regular expressions
import re

# create the list of student names
names = ['SamWise! Gamgee', ' Frodo Baggins111 ', '*Pippin Took*', ' Merry Brandybuck', 
         ' Galadriel30', 'Gandalf:', 'Gollum.', 'Elrond?', 'Gimli', ' Legolas ', '!Arwen#', ' Boromir? ', '#Aragorn# ']

# characters to remove from the names
remove_chars = '[.,:_!#?*0-9]'

# create a function that removes remove_chars from a given name and coverts to title case
def clean_names(name):
    name = name.strip() #remove the beginning and ending white spaces and new lines
    name = re.sub(remove_chars, '', name)  #remove unwanted characters
    name = name.title() #first letter capital 
    return name

# Clean the names of the students

cleaned_names = [clean_name(name) for name in names]

print(cleaned_names)

['Samwise Gamgee', 'Frodo Baggins', 'Pippin Took', 'Merry Brandybuck', 'Galadriel', 'Gandalf', 'Gollum', 'Elrond', 'Gimli', 'Legolas', 'Arwen', 'Boromir', 'Aragorn']


In [25]:
# Part 2
# create a list of student IDs such that 'Samwise Gamgee' has ID QMUL_PhD_BA_1, 'Frodo Baggins' has ID QMUL_PhD_BA_2, etc.
prefix = 'QMUL_PhD_BA'
student_ids = []

for i in range(len(cleaned_names)):
    student_ids.append('QMUL_PhD_BA_' + str(i + 1))

# list of grades
grades = [90, 76, 55, 57, 82, 85, 68, 65, 63, 74, 71, 43, 78]

# write a function that returns F, P, M, or D depensing on the score
def get_grade(score):
    if score < 50:
        return 'F'   # Fail
    elif score < 60:
        return 'P'   # Pass
    elif score < 70:
        return 'M'   # Merit
    else:
        return 'D'   # Distinction

In [26]:
# calculate student mark class and store it as a list
student_class = [get_grade(score) for score in grades]

In [27]:
# Create a dictionary with the student ID as the key and tuple of student name, grade, and grade class as value,
# e.g. 'QMUL_PhD_BA1': ('Samwise Gamgee', 90, 'D'), 'QMUL_PhD_BA2': ('Frodo Baggins', 76, 'D' ...
# Hint: You can use zip at two levels inside zip the lists to create the tupples and then zip again with the keys
students = dict(zip(student_ids, zip(cleaned_names, grades, student_class)))


print(students)
# print the dictionary 
students

{'QMUL_PhD_BA_1': ('Samwise Gamgee', 90, 'D'), 'QMUL_PhD_BA_2': ('Frodo Baggins', 76, 'D'), 'QMUL_PhD_BA_3': ('Pippin Took', 55, 'P'), 'QMUL_PhD_BA_4': ('Merry Brandybuck', 57, 'P'), 'QMUL_PhD_BA_5': ('Galadriel', 82, 'D'), 'QMUL_PhD_BA_6': ('Gandalf', 85, 'D'), 'QMUL_PhD_BA_7': ('Gollum', 68, 'M'), 'QMUL_PhD_BA_8': ('Elrond', 65, 'M'), 'QMUL_PhD_BA_9': ('Gimli', 63, 'M'), 'QMUL_PhD_BA_10': ('Legolas', 74, 'D'), 'QMUL_PhD_BA_11': ('Arwen', 71, 'D'), 'QMUL_PhD_BA_12': ('Boromir', 43, 'F'), 'QMUL_PhD_BA_13': ('Aragorn', 78, 'D')}


{'QMUL_PhD_BA_1': ('Samwise Gamgee', 90, 'D'),
 'QMUL_PhD_BA_2': ('Frodo Baggins', 76, 'D'),
 'QMUL_PhD_BA_3': ('Pippin Took', 55, 'P'),
 'QMUL_PhD_BA_4': ('Merry Brandybuck', 57, 'P'),
 'QMUL_PhD_BA_5': ('Galadriel', 82, 'D'),
 'QMUL_PhD_BA_6': ('Gandalf', 85, 'D'),
 'QMUL_PhD_BA_7': ('Gollum', 68, 'M'),
 'QMUL_PhD_BA_8': ('Elrond', 65, 'M'),
 'QMUL_PhD_BA_9': ('Gimli', 63, 'M'),
 'QMUL_PhD_BA_10': ('Legolas', 74, 'D'),
 'QMUL_PhD_BA_11': ('Arwen', 71, 'D'),
 'QMUL_PhD_BA_12': ('Boromir', 43, 'F'),
 'QMUL_PhD_BA_13': ('Aragorn', 78, 'D')}

# 2. Numpy Exercize

In [28]:
import numpy as np

# 1. Append a list to the end of an array
#Hint: Use the append function

arr1 = np.array([1, 2, 3, 4])

# Create a list of odd numbers from 5 to 25 (inclusive)
list1 = list(range(5, 26, 2))

# append list1 to  arr1 
arr2 = np.append(arr1, list1)

#print arr2
arr2

array([ 1,  2,  3,  4,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25])

In [29]:
# 2.Test which elements of an array is contained in another array
# Hint use the numpy isin function

list2 = [0, -1, 1]
list3 = [9, -7, 1, 0, 0.01]

# Check whether the elements of list2 are in list3
np.isin(list3, list2)

array([False, False,  True,  True, False])

In [30]:
# 3. Flatten a given list

list4 = [[9, 7, -3], [1, 0, 9], [-2, np.nan, np.inf]]

# Flatten list4
arr4 = np.array(list4).flatten()
# Print arr4
arr4

array([ 9.,  7., -3.,  1.,  0.,  9., -2., nan, inf])

In [31]:
arr4.copy()

array([ 9.,  7., -3.,  1.,  0.,  9., -2., nan, inf])

In [32]:
# 4. Write a function to find the value of the smallest entry in an array for which the value is equal to greater than the mean 

def greater_than_mean_fn(arr):
    # Create a copy of the arr array
    x = arr.copy()
    # Sort x (note: arr remains untouched)
    x.sort()
    # Find the first value that is larger the mean of the array
    # Hint: the list is already sorted. Filter according to whether greater than or equal to the mean and choose the one
    # with zero index
    val = x[x >= np.mean(x)][0]
    return val

# Test with arr5
arr5 = np.array([13, 6, -2, 8, 3, 7, 4])

# What is the smallest value in arr5 that is greater than its mean?
greater_than_mean_fn(arr5)

np.int64(6)

In [33]:
# 5. Swap two rows in a 2d Numpy array

# Create a 4-by-5 2d numpy array of random integers from 0 to 100
arr6 = np.random.randint(0, 101, size=(4, 5))
print('Before swap: \n', arr6)

# Swap the first and last rows
arr6[[0,-1]] = arr6[[-1, 0]]
print('After swap: \n', arr6)

Before swap: 
 [[34 48 48 45 19]
 [41  3 67 44 89]
 [31 78 28 23 66]
 [91 56 87 36 67]]
After swap: 
 [[91 56 87 36 67]
 [41  3 67 44 89]
 [31 78 28 23 66]
 [34 48 48 45 19]]
